version: "3.8"

services:
  database:
    image: postgres:13.2-alpine
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env.${ENVIRONMENT}
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT_INTERNAL}"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d/
    networks:
      - db-network

  flyway:
    image: flyway/flyway:9.0.0
    container_name: ${FLYWAY_CONTAINER_NAME}
    env_file: .env.${ENVIRONMENT}
    command: -url=jdbc:postgresql://${POSTGRES_HOST}:${DB_PORT_INTERNAL}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - database
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
